# Generated by Django 5.2.2 on 2025-06-08 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_purchase_product_remove_sale_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('pcs', 'Pieces'), ('litre', 'Litre'), ('box', 'Box'), ('bag', 'Bag')], default='pcs', max_length=20)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expected_selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
    ]
